prgrms-be-devcourse/BE-04-GosuCatcher

src/main/java/com/foo/gosucatcher/config/JpaConfig.java

어떤 변경 사항이 있나요?
- Jpa Config를 따로 클래스로 빼어 추가하였습니다.
- 슬라이스 테스트에 JPA를 용이하게 사용하기 위해 따로 클래스로 분리하여 Jpa Config를 설정해 주었습니다.
- [GS-29](https://gosu-catcher.atlassian.net/browse/GS-29) 
화이팅
[GS-29]: https://gosu-catcher.atlassian.net/browse/GS-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-29] JPA Config 설정

---

.gitignore

어떤 변경 사항이 있나요?
(jira 테스트용) db 관련 설정 yaml 파일 gitignore에 추가
(jira 테스트용) db 관련 설정 yaml 파일 gitignore에 추가
- [GS-31](https://gosu-catcher.atlassian.net/browse/GS-31) 
jira 테스트용 PR입니다
[GS-31]: https://gosu-catcher.atlassian.net/browse/GS-31?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-31] (jira 테스트)  gitignore 에 DB yaml 파일 추가

---

src/main/java/com/foo/gosucatcher/domain/chat/domain/ChattingMessage.java
src/main/java/com/foo/gosucatcher/domain/chat/domain/ChattingRoom.java
src/main/java/com/foo/gosucatcher/domain/estimate/domain/ExpertResponseEstimate.java
src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/Profile.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/ProfileItem.java
src/main/java/com/foo/gosucatcher/domain/item/domain/MainItem.java
src/main/java/com/foo/gosucatcher/domain/item/domain/SubItem.java
src/main/java/com/foo/gosucatcher/domain/member/domain/Member.java
src/main/java/com/foo/gosucatcher/domain/review/domain/Review.java
src/main/java/com/foo/gosucatcher/global/BaseEntity.java

어떤 변경 사항이 있나요?
- 기본적인 엔티티를 구성하였습니다.
- 연관관계는 설정되어 있지 않습니다. 개발하시면서 추가 수정 부탁드립니다.
- [GS-26](https://gosu-catcher.atlassian.net/browse/GS-26) 
[GS-26]: https://gosu-catcher.atlassian.net/browse/GS-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-26] 엔티티 구성

---

README.md
src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
src/main/java/com/foo/gosucatcher/global/error/ErrorResponse.java
src/main/java/com/foo/gosucatcher/global/error/GlobalExceptionHandler.java
src/main/java/com/foo/gosucatcher/global/error/exception/BusinessException.java
src/main/java/com/foo/gosucatcher/global/error/exception/EntityNotFoundException.java
src/main/java/com/foo/gosucatcher/global/error/exception/InvalidValueException.java

어떤 변경 사항이 있나요?
- 예외 및 예외 핸들러 구성(서비스 예외, 에러코드 미작성)
- 예외 및 예외 핸들러 구성
- [GS-27](https://gosu-catcher.atlassian.net/browse/GS-27) 
[GS-27]: https://gosu-catcher.atlassian.net/browse/GS-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-27] 예외 및 예외 핸들러 구성 

---

src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
src/main/java/com/foo/gosucatcher/global/error/ErrorResponse.java
src/main/java/com/foo/gosucatcher/global/error/GlobalExceptionHandler.java
src/main/java/com/foo/gosucatcher/global/error/exception/EntityNotFoundException.java
src/main/java/com/foo/gosucatcher/global/error/exception/InvalidValueException.java

어떤 변경 사항이 있나요?
- Global Exception Handler 내용 추가 하였습니다.
- ErrorResponse 내용 수정하였습니다.
- Global Exception Handler에 예외들 핸들러를 추가했습니다
- 비즈니스
- InvalidValue
- EntityNotFound
- @Validate 검증시 관련 데이터를 깔끔하게 받기위해 ErrorResponse를 수정하였습니다. (List 형태)
- [GS-32](https://gosu-catcher.atlassian.net/browse/GS-32) 
빠른 리뷰 부탁드립니다.
[GS-32]: https://gosu-catcher.atlassian.net/browse/GS-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-32] 예외 핸들러 내용 추가/수정 

---

src/main/java/com/foo/gosucatcher/domain/chat/domain/ChattingMessage.java
src/main/java/com/foo/gosucatcher/domain/chat/domain/ChattingRoom.java
src/main/java/com/foo/gosucatcher/domain/estimate/domain/ExpertResponseEstimate.java
src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberRequestEstimate.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/Expert.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertItem.java
src/main/java/com/foo/gosucatcher/domain/item/domain/MainItem.java
src/main/java/com/foo/gosucatcher/domain/item/domain/SubItem.java
src/main/java/com/foo/gosucatcher/domain/member/domain/Member.java
src/main/java/com/foo/gosucatcher/domain/review/domain/Review.java

어떤 변경 사항이 있나요?
- 엔티티 별 연관관계를 설정했습니다.
- Code with me로 함께 엔티티 별 연관관계를 설정했습니다. 개발하면서 각자 추가로 수정할 것이 있다면 알리고 수정하면 될 것 같습니다.
- [GS-34](https://gosu-catcher.atlassian.net/browse/GS-34) 
[GS-34]: https://gosu-catcher.atlassian.net/browse/GS-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-34] 엔티티 별 연관관계 설정

---

src/main/java/com/foo/gosucatcher/domain/expert/infrastructure/ExpertRepository.java
src/main/java/com/foo/gosucatcher/domain/member/domain/MemberRepository.java
src/main/java/com/foo/gosucatcher/domain/review/domain/ReviewRepository.java

어떤 변경 사항이 있나요?
- review/expert/member 도메인의 repository 추가
- review/expert/member 도메인의 repository 추가
- [GS-36](https://gosu-catcher.atlassian.net/browse/GS-36) 
review/expert/member 도메인 영향 받는 파트들 개발 중인분들 빠르게 pull 한 후에 작업해 주세요
[GS-36]: https://gosu-catcher.atlassian.net/browse/GS-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-36] review/expert/member 도메인의 repository 추가

---

src/main/java/com/foo/gosucatcher/GosuCatcherApplication.java
src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
src/main/java/com/foo/gosucatcher/domain/expert/application/dto/request/ExpertCreateRequest.java
src/main/java/com/foo/gosucatcher/domain/expert/application/dto/request/ExpertUpdateRequest.java
src/main/java/com/foo/gosucatcher/domain/expert/application/dto/response/ExpertResponse.java
src/main/java/com/foo/gosucatcher/domain/expert/application/dto/response/ExpertsResponse.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/Expert.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertRepository.java
src/main/java/com/foo/gosucatcher/domain/expert/presentation/ExpertController.java
src/main/java/com/foo/gosucatcher/domain/review/domain/ReviewRepository.java
src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
src/test/java/com/foo/gosucatcher/domain/expert/presentation/ExpertControllerTest.java

어떤 변경 사항이 있나요?
- 고수 프로필 CRUD를 진행했습니다.
- 고수 전환시 필요한 memberId는 @RequestParam으로 받도록 했습니다.
- 고수 프로필과 관련된 기본적인 CRUD를 구현했습니다.
- 컨트롤러 테스트를 진행했습니다.
- [GS-37](https://gosu-catcher.atlassian.net/browse/GS-37) 
- 현재 인덴트 설정 관련해서 다소 문제가 있는데, 이부분 스크럼 때 질문드린 뒤 바로 수정하겠습니다!
[GS-37]: https://gosu-catcher.atlassian.net/browse/GS-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-37] 고수 프로필 CRUD 구현

---

src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java

어떤 변경 사항이 있나요?
ErrorCode 클래스에 손실된 코드 복구

hotfix: ErrorCode 클래스에 손실된 코드 복구

---

src/main/java/com/foo/gosucatcher/domain/chat/application/MessageService.java
src/main/java/com/foo/gosucatcher/domain/estimate/application/ExpertEstimateService.java
src/main/java/com/foo/gosucatcher/domain/estimate/application/MemberEstimateService.java
src/main/java/com/foo/gosucatcher/domain/estimate/application/dto/response/MemberEstimateResponse.java
src/main/java/com/foo/gosucatcher/domain/estimate/domain/MemberEstimate.java
src/main/java/com/foo/gosucatcher/domain/estimate/domain/Status.java
src/main/java/com/foo/gosucatcher/domain/estimate/presentation/ExpertEstimateController.java
src/main/java/com/foo/gosucatcher/domain/estimate/presentation/MemberEstimateController.java
src/main/java/com/foo/gosucatcher/domain/matching/application/MatchingService.java
src/test/java/com/foo/gosucatcher/domain/estimate/presentation/ExpertEstimateControllerTest.java
src/test/java/com/foo/gosucatcher/domain/estimate/presentation/MemberEstimateControllerTest.java

어떤 변경 사항이 있나요?
- 고객이 특정 고수에게  일반 견적서를 보내고, 고수가 응답하는 견적서를 보내면 채팅방을 만들고 채팅 메시지를 보내는 기능을 구현했습니다.
- 바로 견적과는 달리 일반 견적은 고객의 요청 견적서와 고수 응답 견적서가 1:1로 이루어집니다. 따라서 채팅방은 1개만 만들어지게 됩니다.
(순서 : 고객이 고수에게 견적 요청서 보냄 -> 고수가 응답 견적서를 보냄과 동시에 채팅방 만들고 메시지 전송)
- MemberEstimate와 Expert가 연관 관계를 맺고, MemberEstimate에 Status Enum 필드를 추가하여 고수에게 요청은 했으나 응답 견적서가 오지 않은 상태(PENDING), 고수에게 응답 견적서를 받고 채팅방이 열린 상태(PROCEEDING), 고객 요청 견적서를 마감한 상태(FINISHED)로 견적서의 상태를 구분합니다.
- [GS-58](https://gosu-catcher.atlassian.net/browse/GS-58) 
- 홍섭님과 페어 프로그래밍을 진행했습니다!
[GS-58]: https://gosu-catcher.atlassian.net/browse/GS-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-58] 일반 견적 처리 기능 구현

---

src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
src/main/java/com/foo/gosucatcher/domain/expert/application/dto/response/ExpertResponse.java
src/main/java/com/foo/gosucatcher/domain/expert/application/dto/response/SlicedExpertsResponse.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/SortType.java
src/main/java/com/foo/gosucatcher/domain/expert/presentation/ExpertController.java
src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
src/test/java/com/foo/gosucatcher/domain/expert/presentation/ExpertControllerTest.java

어떤 변경 사항이 있나요?
고수 도메인 내 고수찾기를 위한 정렬기준을 추가했습니다.
- Expert 컨트롤러 내 고수찾기 메서드 내 정렬 기준 검증 로직을 추가했습니다.
- 이와 관련해 ErrorCode를 추가했습니다(E004)
- SortType을 두어 정렬기준을 Enum으로 관리하고, 파라미터로 들어온 정렬기준을 검증합니다.
- 평점순 조회 예시입니다:
- 잘못된 정렬 기준으로 요청이 들어온 예시입니다:
- [GS-61](https://gosu-catcher.atlassian.net/browse/GS-61) 
- 기타 수정 및 요청사항이 있으신 부분들이 있으시면 말씀 부탁드립니다!
[GS-61]: https://gosu-catcher.atlassian.net/browse/GS-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-61] 고수 서비스,지역 None 평점순 조회

---

src/main/java/com/foo/gosucatcher/domain/chat/application/dto/response/ChattingRoomResponse.java
src/main/java/com/foo/gosucatcher/domain/estimate/application/dto/response/ExpertAutoEstimatesResponse.java
src/main/java/com/foo/gosucatcher/domain/estimate/domain/ExpertEstimateRepository.java

어떤 변경 사항이 있나요?
- 바로 매칭 서비스에서 문제가 되었던 N+1 문제 최적화 하였습니다.
- **바로 매칭**의 경우 매칭시의 비즈니스 로직의 몸집이 큰 기능입니다. 하여 얽힌 코드속에서 `insert,select,update` 문이 많이 나가게 되었습니다.
- 특히 유저가 요청한 요청서 조건에 맞는 고수의 견적서가 발견(매칭)이 된다면 **해당 고수가 등록한 고수 견적서가 고수 정보까지 지연 로딩으로 설정되어 있으므로 모두 select 절이 나가게 됩니다. 즉 N+1 문제가 생깁니다.** `(insert, update문을 제외해도, 한 유저의 바로 요청에 나갈 수 있는 select 절은 최대 10명의 고수 견적서와 매칭 된다면, 해당 10명의 고수 정보까지 select문을 날리게 됩니다. = 즉 10번의 select 문)`
- 해당 기능은 숨고 사이트에서 가장 핵심적인 기능이므로 최적화가 필요 하다고 생각했습니다! 
- 또한 숨고 사이트와 동일하게 조건에 맞는 최대 10명의 견적서와 매칭을 시켜주는 것으로 제한했지만, **한 유저만 요청하는 것이 아닌 많은 유저가 동시에 요청을 할 시에 성능의 문제가 있다고 판단**하였습니다.
- **매칭된 고수 견적서의 관련 서비스, 고수 정보까지 함께 데이터를 퍼오는 쿼리문을 작성하여 해결했습니다.**
- [GS-89](https://gosu-catcher.atlassian.net/browse/GS-89) 
드디어 해결 했습니다!~
[GS-89]: …

[GS-89] 바로 매칭 서비스 N+1 쿼리 최적화

---

src/main/java/com/foo/gosucatcher/domain/expert/application/ExpertService.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertImage.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertImageRepository.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertItemRepository.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertRepository.java
src/main/java/com/foo/gosucatcher/domain/expert/presentation/ExpertController.java
src/main/java/com/foo/gosucatcher/domain/image/application/dto/response/ImageResponse.java
src/main/java/com/foo/gosucatcher/domain/image/domain/Image.java
src/main/java/com/foo/gosucatcher/domain/image/infrastructure/FileSystemExpertImageService.java
src/main/java/com/foo/gosucatcher/global/error/exception/ImageIOException.java
src/test/java/com/foo/gosucatcher/domain/expert/presentation/ExpertControllerTest.java

어떤 변경 사항이 있나요?
이미지 서비스 구현체 변경에 따라 컨트롤러 내 로직의 수정이 다소있어, 해당 부분 반영하였습니다.
- ExpertController에서 ImageService를 호출하는 기존의 시스템을, ExpertService에서 ImageService를 호출하도록 변경했습니다.
- ExpertImage 엔티티 내 사용되지 않는 필드들을 삭제했습니다.
- ExpertControllerTest 내 이미지 관련 테스트 코드를 재작성했습니다. 
- [GS-90](https://gosu-catcher.atlassian.net/browse/GS-90) 
- 현재 FileSystem을 활용한 Image 서비스 코드를 제거했습니다. 하지만 빌드를 위해 클래스파일은 남겨두었습니다. 이후 S3를 사용한 서비스 구현체가 들어올 경우 삭제할 예정입니다!
[GS-90]: https://gosu-catcher.atlassian.net/browse/GS-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-90] 고수 도메인 내 이미지 관련 코드 리팩토링

---

src/main/java/com/foo/gosucatcher/config/SecurityConfig.java
src/main/java/com/foo/gosucatcher/domain/bucket/domain/Bucket.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/Expert.java
src/main/java/com/foo/gosucatcher/domain/expert/domain/ExpertRepository.java
src/main/java/com/foo/gosucatcher/domain/member/application/MemberAuthService.java
src/main/java/com/foo/gosucatcher/domain/member/application/MemberProfileService.java
src/main/java/com/foo/gosucatcher/domain/member/application/MemberSmsAuthService.java
src/main/java/com/foo/gosucatcher/domain/member/application/dto/response/JwtReissueResponse.java
src/main/java/com/foo/gosucatcher/domain/member/domain/MemberRepository.java
src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberAuthController.java
src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberEmailAuthController.java
src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberSmsAuthController.java
src/main/java/com/foo/gosucatcher/global/aop/CurrentMemberIdAop.java
src/main/java/com/foo/gosucatcher/global/error/ErrorCode.java
src/main/java/com/foo/gosucatcher/global/error/GlobalExceptionHandler.java
src/main/java/com/foo/gosucatcher/global/error/exception/AopException.java
src/main/java/com/foo/gosucatcher/global/error/exception/HttpHeaderException.java
src/main/java/com/foo/gosucatcher/global/security/CustomUserDetailsService.java
src/main/java/com/foo/gosucatcher/global/security/JwtAuthenticationFilter.java
src/main/java/com/foo/gosucatcher/global/security/JwtProperties.java
src/main/java/com/foo/gosucatcher/global/security/JwtTokenProvider.java
src/main/resources/application.yml

어떤 변경 사항이 있나요?
Access Token이 만료되었을 경우 재발급하는 메서드를 구현, 그 외에 자잘한 버그 픽스
처음에는 필터를 활용해서 만료된 액세스 토큰을 인식하고 재발급하도록 기능을 구현하려 했으나,
코드를 다 작성하고 난 후, 새로 발급한 토큰이 사용되지 않고 만료된 토큰이 계속 사용되는 버그가 있어서,
결국 방향성을 돌리게 됐습니다...! 아래의 두 링크를 참고하여 구현했습니다.
[1번 링크](https://velog.io/@bum12ark/MSA-JWT-%EC%9D%B8%EC%A6%9D-%EC%84%9C%EB%B2%84-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0-2.reissu)
[2번 링크](https://junhyunny.github.io/spring-boot/spring-security/issue-and-reissue-json-web-token/)
기능에 관한 유저 스토리는 다음과 같습니다.
- ### 만료된 액세스 토큰과 만료되지 않은 리플래시 토큰을 사용하는 경우
1. 유저가 만료된 액세스 토큰으로 프로필 수정을 요청 -> 401 에러와 함께 토큰이 만료됐다는 메시지를 프론트엔드가 받음
2. 401에러를 받은 프론트엔드는 재발급 엔드포인트인 '/api/v1/members/reissue'로 리플래시 토큰과 함께 요청을 보냄
3. 리플래시 토큰을 서버에 저장된 리플래시 토큰과 동일함을 검증하고 새로운 액세스 토큰을 발급해서 프론트에 전달
4. 프론트는 새로운 액세스 토큰을 브라우저에 저장하게 하고 새로운 토큰으로 이전에 진행하던 프로필 수정 요청을 처리함
- …

[GS-77] 만료된 access token 재발급

---

src/main/java/com/foo/gosucatcher/domain/chat/application/MessageService.java
src/main/java/com/foo/gosucatcher/domain/chat/application/dto/request/MessageRequest.java

어떤 변경 사항이 있나요?
- 요청서&견적서 간 메시지 전송 시 sender Id가 전송되는 부분을 수정&리팩토링 했습니다.
- 첫 Message를 보내는 sender Id에는 메시지를 보내는 사람(expert)의 member Id가 들어가도록  수정했습니다. 아래 결과로 확인하실 수 있습니다.
- [GS-105](https://gosu-catcher.atlassian.net/browse/GS-105) 
[GS-105]: https://gosu-catcher.atlassian.net/browse/GS-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-105] 요청서-견적서 Message 서비스 리팩토링

---

src/test/java/com/foo/gosucatcher/domain/review/presentation/ReviewControllerTest.java

어떤 변경 사항이 있나요?
- 이미지를 포함한 리뷰 작성 컨트롤러 테스트
- 리뷰에 이미지를 추가할 수 있도록 코드가 변경됨에 따라 테스트 코드도 수정하였습니다.
- [GS-107](https://gosu-catcher.atlassian.net/browse/GS-107) 
[GS-107]: https://gosu-catcher.atlassian.net/browse/GS-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-107] 이미지를 포함한 리뷰 작성 컨트롤러 테스트

---

src/main/java/com/foo/gosucatcher/view/estimate/MemberEstimateViewController.java
src/main/resources/static/css/estimates/member-estimate.css
src/main/resources/static/js/estimates/member-estimate.js
src/main/resources/templates/estimate/member-estimate.html

어떤 변경 사항이 있나요?
- 고객이 이용하는 견적 요청서의 화면을 구성했습니다.  요청하기 버튼은 일반 견적 생성 메서드(MemberEstimateController의 createNormal 메서드)와 연결해놓았습니다.
- 현재 aop 적용을 하지 않았기 때문에 `MemberEstimateController 클래스의 createNormal 메서드`를 아래와 같이 수정하셔야 정상적으로 작동이 됩니다.
```java
//MemberEstimateController 클래스의 createNormal 메서드
@PostMapping("/normal/{memberId}/{expertId}")
//@CurrentMemberId
public ResponseEntity<MemberEstimateResponse> createNormal(@PathVariable Long memberId, @PathVariable Long expertId, @Validated @RequestBody MemberEstimateRequest memberEstimateRequest) {
MemberEstimateResponse memberEstimateResponse = memberEstimateService.createNormal(memberId, expertId, memberEstimateRequest);
return ResponseEntity.ok(memberEstimateResponse);
}
```
- 지역을 선택하지 않거나, 지역을 시/군/구까지 선택하지 않는다면 팝업창을 띄워 지역을 선택하도록 요구합니다.
<br> <br>
- 서비스 …

[GS-109] 견적 요청서 화면 구성

---

src/main/java/com/foo/gosucatcher/view/estimate/MemberEstimateViewController.java
src/main/resources/static/js/estimates/auto-member-estimate.js
src/main/resources/static/js/estimates/normal-member-estimate.js
src/main/resources/templates/estimates/auto-member-estimate.html
src/main/resources/templates/estimates/normal-member-estimate.html

어떤 변경 사항이 있나요?
- 바로 견적 요청서 화면을 구성했습니다.
- 앞서 올린 일반 견적 PR과 같은 형식인 바로 견적 요청서 화면을 구성했습니다.
- 바로 견적을 추가하면서 구분을 위해 앞서 만든 일반 견적 요청서의 url과 메서드 파라미터를 변경했습니다.
- 실행해보시려면 MemberEstimateController의 메서드 구성을 조금 변경하셔야 합니다.
```java
//MemberEstimateController의 createNormal 메서드
@PostMapping("/normal/{expertId}")
//@CurrentMemberId
public ResponseEntity<MemberEstimateResponse> createNormal(@RequestParam Long memberId, @PathVariable Long expertId, @Validated @RequestBody MemberEstimateRequest memberEstimateRequest) {
MemberEstimateResponse memberEstimateResponse = memberEstimateService.createNormal(memberId, expertId, memberEstimateRequest);
return ResponseEntity.ok(memberEstimateResponse);
}
```
```java
//MemberEstimateController의 createAuto 메서드
@PostMapping("/auto")
//@CurrentMemberId
public …
```

[GS-110] 바로 견적 요청서 화면 구성 & 일반 견적 요청서 수정

---

src/main/java/com/foo/gosucatcher/domain/member/application/MemberAuthService.java
src/main/java/com/foo/gosucatcher/domain/member/domain/MemberImage.java
src/main/resources/templates/experts/experts.html

어떤 변경 사항이 있나요?
- 멤버 회원가입시 이미지 초기화 메서드를 추가했습니다.
- 멤버 회원가입시 이미지 초기화 메서드를 추가했습니다.
- [GS-108](https://gosu-catcher.atlassian.net/browse/GS-108) 
[GS-108]: https://gosu-catcher.atlassian.net/browse/GS-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-108] 멤버 이미지 초기화

---

src/main/java/com/foo/gosucatcher/view/estimate/ExpertEstimateViewController.java
src/main/java/com/foo/gosucatcher/view/estimate/MemberEstimateViewController.java
src/main/resources/static/js/estimates/auto-expert-estimate.js
src/main/resources/static/js/estimates/normal-member-estimate.js
src/main/resources/templates/estimates/auto-expert-estimate.html
src/main/resources/templates/estimates/normal-member-estimate.html
src/main/resources/templates/layout/nav.html

어떤 변경 사항이 있나요?
- 고수가 바로 견적서를 등록하는 화면을 구성했습니다.
- [GS-113](https://gosu-catcher.atlassian.net/browse/GS-113) 
[GS-113]: https://gosu-catcher.atlassian.net/browse/GS-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-113] 고수 바로 견적서 등록 화면 구성 

---

src/main/resources/static/js/search/search.js
src/main/resources/templates/estimates/auto-member-estimate.html
src/main/resources/templates/layout/nav.html

어떤 변경 사항이 있나요?
- 인기 검색어, 최근 검색어 화면 구현하였습니다.
- 레디스와 연동된 api를 통하여 인기 검색어, 최근검색어 리스트를 구현하였습니다.
- [GS-119](https://gosu-catcher.atlassian.net/browse/GS-119) 
[GS-119]: https://gosu-catcher.atlassian.net/browse/GS-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-119] 최근 검색 + 인기 검색 화면 

---

src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberProfileController.java
src/main/java/com/foo/gosucatcher/view/estimate/ExpertEstimateViewController.java
src/main/resources/static/css/estimates/normal-expert-estimate.css
src/main/resources/static/js/estimates/normal-expert-estimate.js
src/main/resources/templates/estimates/auto-expert-estimate.html
src/main/resources/templates/estimates/normal-expert-estimate.html

어떤 변경 사항이 있나요?
- 고수 일반 견적서 화면을 구성했습니다.
- [GS-121](https://gosu-catcher.atlassian.net/browse/GS-121) 
[GS-121]: https://gosu-catcher.atlassian.net/browse/GS-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-121] 고수 일반 견적서 화면 구성

---

src/main/resources/templates/experts/experts.html

어떤 변경 사항이 있나요?
- hotfix: Expert 뷰 css 파일 링크 수정
- hotfix: Expert 뷰 css 파일 링크 수정
- [GS-XXX]() 

hotfix: Expert 뷰 css 파일 링크 수정

---

src/docs/asciidoc/memberEstimate.adoc
src/test/java/com/foo/gosucatcher/domain/estimate/presentation/MemberEstimateControllerTest.java

어떤 변경 사항이 있나요?
-  회원 견적서 일부 메서드의 레스트 독스 코드를 작성했습니다.
- [GS-128](https://gosu-catcher.atlassian.net/browse/GS-128) 
[GS-128]: https://gosu-catcher.atlassian.net/browse/GS-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-128] 레스트 독스 - 회원 견적서

---

src/docs/asciidoc/mainItem.adoc
src/main/java/com/foo/gosucatcher/domain/item/application/MainItemService.java
src/main/java/com/foo/gosucatcher/domain/item/presentation/MainItemController.java
src/test/java/com/foo/gosucatcher/domain/item/presentation/MainItemControllerTest.java

어떤 변경 사항이 있나요?
- [GS-126](https://gosu-catcher.atlassian.net/browse/GS-126) 
[GS-126]: https://gosu-catcher.atlassian.net/browse/GS-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GS-129] 메인 아이템 명세 추가

---

src/main/java/com/foo/gosucatcher/domain/expert/presentation/ExpertController.java

docs: Expert 컨트롤러 내 swagger 관련 어노테이션 추가

---

src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberAuthController.java
src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberEmailAuthController.java
src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberProfileController.java
src/main/java/com/foo/gosucatcher/domain/member/presentation/MemberSmsAuthController.java

[GS-134] 레스트 독스 - 프로필 테스트 
